import { useEffect, useMemo, useState } from "react";
import type { BookingTransactionType, HotelBooking, HotelBookingInput, HotelBookingLineInput, HotelRoomType, Party } from "./db";
import { createHotelBooking, getHotelBookings, updateHotelBooking, voidHotelBooking } from "./db";
import ProgressiveBookingIdentity from "./ProgressiveBookingIdentity";
import { bookingDigitsFromUb, normalizeBookingUb } from "./bookingUb";
import { updateHotelAdditionalDetails } from "./ProgressiveBookingDb";

type Props={companyId:string;parties:Party[];transactionType:BookingTransactionType;userId?:string;canCreate?:boolean;canEdit?:boolean;canVoid?:boolean;onBack:()=>void;onChanged?:()=>void|Promise<void>};
type Row={rowId:string;city:string;hotelName:string;checkIn:string;checkOut:string;nights:string;roomType:HotelRoomType|"";rate:string;quantity:string;roe:string};
type Mode="FORM"|"REGISTER";type Filter="ALL"|BookingTransactionType;
const roomTypes:Array<{value:HotelRoomType;label:string}>=[{value:"SHARING",label:"Sharing"},{value:"QUINT_SHARING",label:"Quint / Sharing"},{value:"QUAD",label:"Quad"},{value:"TRIPLE",label:"Triple"},{value:"DOUBLE",label:"Double"},{value:"SUITE_ROOM",label:"Suite Room"}];
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function num(v:string){const n=Number(v);return Number.isFinite(n)?n:0} function whole(v:string){return Math.max(0,Math.trunc(num(v)))}
function nights(a:string,b:string){if(!a||!b||b<=a)return 0;const[x,y,z]=a.split("-").map(Number),[p,q,r]=b.split("-").map(Number);return Math.max(0,Math.floor((Date.UTC(p,q-1,r)-Date.UTC(x,y-1,z))/86400000))}
function newRow(roe=""):Row{return{rowId:crypto.randomUUID(),city:"",hotelName:"",checkIn:"",checkOut:"",nights:"",roomType:"",rate:"",quantity:"",roe}}
function hasData(r:Row){return Boolean(r.city.trim()||r.hotelName.trim()||r.checkIn||r.checkOut||r.roomType||r.rate.trim()||r.quantity.trim()||r.roe.trim())}
function sarTotal(r:Row){return Math.max(0,num(r.rate))*whole(r.nights)*whole(r.quantity)} function pkrTotal(r:Row){const x=Math.max(0,num(r.roe));return x>0?sarTotal(r)*x:0}
function sar(v:number){return `SAR ${Number(v||0).toLocaleString("en-PK",{maximumFractionDigits:2})}`} function pkr(v:number){return `Rs ${Number(v||0).toLocaleString("en-PK",{maximumFractionDigits:2})}`}

export default function HotelBookingFlowV2({companyId,parties,transactionType,userId="",canCreate=true,canEdit=true,canVoid=true,onBack,onChanged}:Props){
 const[mode,setMode]=useState<Mode>("FORM");const[tx,setTx]=useState<BookingTransactionType>(transactionType);const[counterpartyId,setCounterpartyId]=useState("");const[bookingDate,setBookingDate]=useState(localDate());const[ubDigits,setUbDigits]=useState("");const[ubNumber,setUbNumber]=useState("");const[assigned,setAssigned]=useState(false);const[saved,setSaved]=useState(false);const[detailsOpen,setDetailsOpen]=useState(false);const[rows,setRows]=useState<Row[]>([newRow()]);
 const[confirmationVoucher,setConfirmationVoucher]=useState("");const[mealPlan,setMealPlan]=useState("");const[guestFamilyName,setGuestFamilyName]=useState("");const[guestCount,setGuestCount]=useState("");const[customerContact,setCustomerContact]=useState("");const[specialRequests,setSpecialRequests]=useState("");const[notes,setNotes]=useState("");
 const[entries,setEntries]=useState<HotelBooking[]>([]);const[editingId,setEditingId]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const[search,setSearch]=useState("");const[filter,setFilter]=useState<Filter>("ALL");
 useEffect(()=>{if(!editingId)setTx(transactionType)},[transactionType,editingId]);useEffect(()=>{void loadEntries("")},[companyId]);
 const summary=useMemo(()=>{let stays=0,allNights=0,rooms=0,beds=0,totalSar=0,totalPkr=0,pending=0;rows.forEach(r=>{if(!hasData(r))return;stays++;allNights+=whole(r.nights);const q=whole(r.quantity);if(r.roomType==="SHARING")beds+=q;else rooms+=q;const s=sarTotal(r);totalSar+=s;if(num(r.roe)>0)totalPkr+=pkrTotal(r);else pending+=s});return{stays,nights:allNights,rooms,beds,totalSar,totalPkr,pending}},[rows]);
 const visible=entries.filter(e=>filter==="ALL"||e.transaction_type===filter);
 async function loadEntries(q=search){try{setEntries(await getHotelBookings(companyId,q))}catch(e){setError(e instanceof Error?e.message:String(e))}}
 function reset(){setTx(transactionType);setCounterpartyId("");setBookingDate(localDate());setUbDigits("");setUbNumber("");setAssigned(false);setSaved(false);setDetailsOpen(false);setRows([newRow()]);setConfirmationVoucher("");setMealPlan("");setGuestFamilyName("");setGuestCount("");setCustomerContact("");setSpecialRequests("");setNotes("");setEditingId(null);setError("");setMessage("")}
 function assign(formatted:string){setError("");if(!counterpartyId)return setError(tx==="SALE"?"Select a Party / Customer first.":"Select a Vendor / Supplier first.");if(!bookingDate)return setError("Date of Booking is required.");if(!formatted)return setError("Enter a booking number using 1 to 4 digits.");const dup=entries.find(e=>normalizeBookingUb(e.ub_number)===formatted&&(tx==="SALE"?e.transaction_type==="SALE":e.transaction_type==="PURCHASE"&&e.counterparty_id===counterpartyId));if(dup)return setError(tx==="SALE"?`${formatted} already has a Hotel Sale booking.`:`This Vendor already has a Hotel Purchase booking for ${formatted}.`);setUbNumber(formatted);setAssigned(true);setMessage(`${formatted} is ready. Enter Hotel Details & Rates below.`)}
 function update(id:string,patch:Partial<Row>){setRows(c=>c.map(r=>{if(r.rowId!==id)return r;const n={...r,...patch};n.nights=nights(n.checkIn,n.checkOut)?String(nights(n.checkIn,n.checkOut)):"";return n}))} function add(){const inherited=[...rows].reverse().find(r=>r.roe.trim())?.roe||"";setRows(c=>[...c,newRow(inherited)])} function remove(id:string){setRows(c=>{const n=c.filter(r=>r.rowId!==id);return n.length?n:[newRow()]})}
 function lines():HotelBookingLineInput[]{return rows.filter(hasData).map(r=>({city:r.city.trim(),hotelName:r.hotelName.trim(),checkIn:r.checkIn,checkOut:r.checkOut,nights:whole(r.nights),roomType:r.roomType as HotelRoomType,ratePerNightSar:Math.max(0,num(r.rate)),quantity:whole(r.quantity),roe:r.roe.trim()===""?null:Math.max(0,num(r.roe))}))}
 function input(includeDetails=true):HotelBookingInput{return{transactionType:tx,counterpartyId,transactionDate:bookingDate,ubNumber,confirmationVoucher:includeDetails?confirmationVoucher:"",mealPlan:includeDetails?mealPlan:"",guestFamilyName:includeDetails?guestFamilyName:"",guestCount:includeDetails?whole(guestCount):0,customerContact:includeDetails?customerContact:"",specialRequests:includeDetails?specialRequests:"",notes:includeDetails?notes:"",lines:lines()}}
 async function saveCommercial(){if(!assigned)return setError("Create / Assign the Booking UB first.");setBusy(true);setError("");try{if(editingId){await updateHotelBooking(companyId,editingId,input(true),userId);setMessage(`Hotel Details & Rates for ${ubNumber} updated.`)}else{const id=await createHotelBooking(companyId,input(false),userId);setEditingId(id);setSaved(true);setMessage(`Hotel booking ${ubNumber} saved. Optional Guest / Reservation Details are now available.`)}setSaved(true);await loadEntries(search);await onChanged?.()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function saveDetails(){if(!editingId)return;setBusy(true);setError("");try{await updateHotelAdditionalDetails(companyId,editingId,{confirmationVoucher,mealPlan,guestFamilyName,guestCount:whole(guestCount),customerContact,specialRequests,notes},userId);setMessage(`Hotel Reservation Details for ${ubNumber} saved.`);await loadEntries(search)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 function edit(e:HotelBooking){if(!canEdit||e.status!=="ACTIVE")return;setTx(e.transaction_type);setCounterpartyId(e.counterparty_id);setBookingDate(e.transaction_date);setUbNumber(e.ub_number);setUbDigits(bookingDigitsFromUb(e.ub_number));setAssigned(true);setSaved(true);setDetailsOpen(false);setConfirmationVoucher(e.confirmation_voucher||"");setMealPlan(e.meal_plan||"");setGuestFamilyName(e.guest_family_name||"");setGuestCount(e.guest_count?String(e.guest_count):"");setCustomerContact(e.customer_contact||"");setSpecialRequests(e.special_requests||"");setNotes(e.notes||"");setRows(e.lines.length?e.lines.map(l=>({rowId:crypto.randomUUID(),city:l.city,hotelName:l.hotel_name,checkIn:l.check_in,checkOut:l.check_out,nights:String(l.nights||""),roomType:l.room_type,rate:String(l.rate_per_night_sar||""),quantity:String(l.quantity||""),roe:Number(l.roe||0)>0?String(l.roe):""})):[newRow()]);setEditingId(e.id);setMode("FORM");setMessage(`Editing Hotel booking ${e.ub_number}. Identity is locked; Section 02 and Section 03 save independently.`);window.scrollTo({top:0,behavior:"smooth"})}
 async function voidEntry(e:HotelBooking){if(!canVoid||e.status!=="ACTIVE"||busy)return;if(!window.confirm(`Void Hotel booking ${e.ub_number}?`))return;setBusy(true);try{await voidHotelBooking(companyId,e.id,userId);await loadEntries(search);await onChanged?.();setMessage(`Hotel booking ${e.ub_number} voided.`)}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}}

 if(mode==="REGISTER")return <section className="booking-entry-screen hotel10-screen"><div className="booking-screen-toolbar"><button className="booking-back-button" onClick={()=>setMode("FORM")}>← Back to Hotel Booking</button><span className="booking-foundation-badge active-engine">HOTEL REGISTER</span></div><div className="hotel10-title-row"><div><span className="eyebrow blue">HOTEL BOOKING REGISTER</span><h2>Hotel Booking Register</h2></div></div><div className="package14-register-controls"><div className="package-register-filter-tabs">{(["ALL","SALE","PURCHASE"] as Filter[]).map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="search-box"><input value={search} onChange={e=>{setSearch(e.target.value);void loadEntries(e.target.value)}} placeholder="Search UB, hotel, city, party/vendor..."/></div></div><div className="party-table-wrap"><table className="party-table"><thead><tr><th>DATE</th><th>UB #</th><th>TYPE</th><th>PARTY / VENDOR</th><th>HOTEL STAYS</th><th>TOTAL SAR</th><th>TOTAL PKR</th><th>PENDING SAR</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{visible.map(e=><tr key={e.id}><td>{e.transaction_date}</td><td><b>{e.ub_number}</b></td><td>{e.transaction_type}</td><td>{e.counterparty_name}</td><td>{e.lines.map(l=>`${l.city}: ${l.hotel_name}`).join(" · ")}</td><td>{sar(e.total_sar)}</td><td>{pkr(e.total_pkr)}</td><td>{sar(e.unconverted_sar)}</td><td><span className={`status ${e.status.toLowerCase()}`}>{e.status}</span></td><td><div className="row-actions"><button disabled={!canEdit||e.status!=="ACTIVE"} onClick={()=>edit(e)}>Edit / Details</button><button disabled={!canVoid||e.status!=="ACTIVE"} onClick={()=>void voidEntry(e)}>Void</button></div></td></tr>)}</tbody></table></div></section>;

 return <section className="booking-entry-screen hotel10-screen package14-page"><div className="booking-screen-toolbar"><button className="booking-back-button" onClick={onBack}>← Back to Booking Services</button><div style={{display:"flex",gap:10,alignItems:"center"}}><span className={`direction-badge ${tx==="SALE"?"sale":"purchase"}`}>{tx==="SALE"?"SALE TO PARTY":"PURCHASE FROM VENDOR / SUPPLIER"}</span><button className="booking-foundation-badge active-engine" onClick={()=>{setMode("REGISTER");void loadEntries(search)}}>Hotel Booking Register</button></div></div><div className="hotel10-title-row"><div><span className="eyebrow blue">HOTEL BOOKING</span><h2>{saved?`Hotel Booking — ${ubNumber}`:"New Hotel Booking"}</h2><p>Create the UB first, save Hotel calculations second, then complete optional reservation details.</p></div></div>{message&&<div className="alert success">{message}</div>}{error&&<div className="alert error">{error}</div>}
 <ProgressiveBookingIdentity companyId={companyId} userId={userId} transactionType={tx} parties={parties} counterpartyId={counterpartyId} onCounterpartyChange={setCounterpartyId} bookingDate={bookingDate} onBookingDateChange={setBookingDate} ubDigits={ubDigits} onUbDigitsChange={setUbDigits} ubNumber={ubNumber} assigned={assigned} saved={saved} onAssign={assign} onEditHeader={()=>{setAssigned(false);setMessage("")}} onAccountsChanged={onChanged} onError={setError} onMessage={setMessage} serviceLabel="Hotel" />
 {assigned&&<section className="hotel10-card"><div className="hotel10-section-head"><span>2</span><b>ACCOMMODATION DETAILS & RATES</b><small>Commercial / accounting hotel rows under {ubNumber}</small></div><div style={{padding:14,textAlign:"right"}}><button className="primary small" onClick={add}>+ Add Hotel Row</button></div><div className="hotel10-table-wrap"><table className="hotel10-table"><thead><tr><th>SR</th><th>CITY</th><th>HOTEL NAME</th><th>CHECK-IN</th><th>CHECK-OUT</th><th>NIGHTS</th><th>ROOM TYPE</th><th>PER NIGHT SAR</th><th>ROOMS / BEDS</th><th>ROE</th><th>TOTAL SAR</th><th>TOTAL PKR</th><th></th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.rowId}><td>{i+1}</td><td><input value={r.city} onChange={e=>update(r.rowId,{city:e.target.value})}/></td><td><input value={r.hotelName} onChange={e=>update(r.rowId,{hotelName:e.target.value})}/></td><td><input type="date" value={r.checkIn} onChange={e=>update(r.rowId,{checkIn:e.target.value})}/></td><td><input type="date" value={r.checkOut} onChange={e=>update(r.rowId,{checkOut:e.target.value})}/></td><td><b>{r.nights||"—"}</b></td><td><select value={r.roomType} onChange={e=>update(r.rowId,{roomType:e.target.value as HotelRoomType})}><option value="">Select</option>{roomTypes.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></td><td><input type="number" value={r.rate} onChange={e=>update(r.rowId,{rate:e.target.value})}/></td><td><input type="number" value={r.quantity} onChange={e=>update(r.rowId,{quantity:e.target.value})}/></td><td><input type="number" value={r.roe} onChange={e=>update(r.rowId,{roe:e.target.value})} placeholder="Optional"/></td><td>{sar(sarTotal(r))}</td><td>{num(r.roe)>0?pkr(pkrTotal(r)):"—"}</td><td><button className="hotel10-remove" onClick={()=>remove(r.rowId)}>×</button></td></tr>)}</tbody></table></div><div className="hotel10-summary-grid"><div><small>HOTEL STAYS</small><b>{summary.stays}</b></div><div><small>TOTAL NIGHTS</small><b>{summary.nights}</b></div><div><small>ROOMS</small><b>{summary.rooms}</b></div><div><small>SHARING BEDS</small><b>{summary.beds}</b></div><div><small>GRAND TOTAL SAR</small><b>{sar(summary.totalSar)}</b></div><div><small>GRAND TOTAL PKR</small><b>{pkr(summary.totalPkr)}</b></div>{summary.pending>0&&<div><small>ROE PENDING SAR</small><b>{sar(summary.pending)}</b></div>}</div><div className="package14-commercial-actions">{saved&&<button className="secondary" onClick={reset}>+ New Hotel Booking</button>}<button className="primary" disabled={busy||(!editingId&&!canCreate)||(!!editingId&&!canEdit)} onClick={()=>void saveCommercial()}>{busy?"Saving...":editingId?`Update Hotel Details & Rates — ${ubNumber}`:`Save Hotel Booking — ${ubNumber}`}</button></div></section>}
 {saved&&editingId&&<section className={`package14-additional ${detailsOpen?"open":"closed"}`}><button className="package14-additional-toggle" onClick={()=>setDetailsOpen(v=>!v)}><span className="package14-step-purple">03</span><div><b>GUEST / RESERVATION DETAILS — {ubNumber}</b><small>Optional reservation information. This section does not change Hotel calculations.</small></div><span className="package14-optional">OPTIONAL</span><strong>{detailsOpen?"Close Details ▲":"+ Open Details ▼"}</strong></button>{detailsOpen&&<div className="package14-additional-body"><div className="package14-details-grid"><label>Lead Guest / Group Name<input value={guestFamilyName} onChange={e=>setGuestFamilyName(e.target.value)}/></label><label>No. of Guests<input type="number" value={guestCount} onChange={e=>setGuestCount(e.target.value)}/></label><label>Hotel Confirmation / Voucher #<input value={confirmationVoucher} onChange={e=>setConfirmationVoucher(e.target.value)}/></label><label>Meal Plan<input value={mealPlan} onChange={e=>setMealPlan(e.target.value)}/></label><label>Customer Contact<input value={customerContact} onChange={e=>setCustomerContact(e.target.value)}/></label><label className="wide">Special Requests<textarea rows={3} value={specialRequests} onChange={e=>setSpecialRequests(e.target.value)}/></label><label className="wide">Internal Notes<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="package14-details-actions"><span>Optional — can be completed later.</span><button className="primary" disabled={busy||!canEdit} onClick={()=>void saveDetails()}>{busy?"Saving...":`Save Hotel Details — ${ubNumber}`}</button></div></div>}</section>}
 {!assigned&&<div className="package14-next-step">Create / Assign a Booking UB to unlock Accommodation Details & Rates.</div>}{assigned&&!saved&&<div className="package14-next-step">Save Section 02 to activate the Hotel booking and unlock Optional Guest / Reservation Details.</div>}
 </section>;
}
