import { useEffect, useMemo, useState } from "react";
import type { BookingTransactionType, Party } from "./db";
import { createMiscBooking, getMiscBookings, initMiscDatabase, updateMiscBooking, voidMiscBooking, type MiscBooking, type MiscBookingInput, type MiscBookingLineInput } from "./miscDb";
import ProgressiveBookingIdentity from "./ProgressiveBookingIdentity";
import { bookingDigitsFromUb, normalizeBookingUb } from "./bookingUb";
import { getMiscOperationalDetails, saveMiscFamilyHeads, saveMiscOperationalDetails, type MiscOperationalRow } from "./MiscOperationalDb";
import "./BookingFinalization.css";

type Props={companyId:string;parties:Party[];transactionType:BookingTransactionType;userId?:string;canCreate?:boolean;canEdit?:boolean;canVoid?:boolean;onBack:()=>void;onChanged?:()=>void|Promise<void>};
type Row={rowId:string;serviceName:string;familyHead:string;paxCount:string;ratePerPerson:string;roe:string};
type OperationalRow=Omit<MiscOperationalRow,"id"|"sortOrder">&{rowId:string};
type Mode="FORM"|"REGISTER";type Filter="ALL"|BookingTransactionType;
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function newRow():Row{return{rowId:crypto.randomUUID(),serviceName:"",familyHead:"",paxCount:"",ratePerPerson:"",roe:""}}
function num(v:string){const n=Number(v);return Number.isFinite(n)?n:0} function whole(v:string){return Math.max(0,Math.trunc(num(v)))}
function pkr(v:number){return `Rs ${Number(v||0).toLocaleString("en-PK",{maximumFractionDigits:2})}`} function sar(v:number){return `SAR ${Number(v||0).toLocaleString("en-PK",{maximumFractionDigits:2})}`}
function calc(row:Row){const pax=whole(row.paxCount),rate=Math.max(0,num(row.ratePerPerson)),roe=Math.max(0,num(row.roe)),base=rate*pax;return roe>0?{mode:"SAR" as const,pax,totalSar:base,totalPkr:base*roe,roe}:{mode:"PKR" as const,pax,totalSar:0,totalPkr:base,roe:0}}
function hasData(row:Row){return Boolean(row.serviceName.trim()||row.familyHead.trim()||row.paxCount.trim()||row.ratePerPerson.trim()||row.roe.trim())}

export default function MiscBookingFlowV3({companyId,parties,transactionType,userId="",canCreate=true,canEdit=true,canVoid=true,onBack,onChanged}:Props){
 const[mode,setMode]=useState<Mode>("FORM");const[tx,setTx]=useState<BookingTransactionType>(transactionType);const[counterpartyId,setCounterpartyId]=useState("");const[bookingDate,setBookingDate]=useState(localDate());const[ubDigits,setUbDigits]=useState("");const[ubNumber,setUbNumber]=useState("");const[assigned,setAssigned]=useState(false);const[saved,setSaved]=useState(false);const[detailsOpen,setDetailsOpen]=useState(false);const[rows,setRows]=useState<Row[]>([newRow()]);const[operationalRows,setOperationalRows]=useState<OperationalRow[]>([]);const[notes,setNotes]=useState("");const[entries,setEntries]=useState<MiscBooking[]>([]);const[editingId,setEditingId]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const[search,setSearch]=useState("");const[filter,setFilter]=useState<Filter>("ALL");
 useEffect(()=>{if(!editingId)setTx(transactionType)},[transactionType,editingId]);useEffect(()=>{void(async()=>{try{await initMiscDatabase();await loadEntries("")}catch(e){setError(e instanceof Error?e.message:String(e))}})()},[companyId]);
 const summary=useMemo(()=>{let services=0,paxEntries=0,totalSar=0,totalPkr=0;rows.forEach((row)=>{if(!hasData(row))return;const c=calc(row);services+=1;paxEntries+=c.pax;totalSar+=c.totalSar;totalPkr+=c.totalPkr});return{services,paxEntries,totalSar,totalPkr}},[rows]);
 const visible=entries.filter((entry)=>filter==="ALL"||entry.transaction_type===filter);
 async function loadEntries(query=search){try{setEntries(await getMiscBookings(companyId,query))}catch(e){setError(e instanceof Error?e.message:String(e))}}
 function reset(){setTx(transactionType);setCounterpartyId("");setBookingDate(localDate());setUbDigits("");setUbNumber("");setAssigned(false);setSaved(false);setDetailsOpen(false);setRows([newRow()]);setOperationalRows([]);setNotes("");setEditingId(null);setError("");setMessage("")}
 function assign(formatted:string){setError("");if(!counterpartyId)return setError(tx==="SALE"?"Select a Party / Customer first.":"Select a Vendor / Supplier first.");if(!bookingDate)return setError("Date of Booking is required.");if(!formatted)return setError("Enter a booking number using 1 to 4 digits.");const duplicate=entries.find((entry)=>normalizeBookingUb(entry.ub_number)===formatted&&(tx==="SALE"?entry.transaction_type==="SALE":entry.transaction_type==="PURCHASE"&&entry.counterparty_id===counterpartyId));if(duplicate)return setError(tx==="SALE"?`${formatted} already has a Misc Sale booking.`:`This Vendor already has a Misc Purchase booking for ${formatted}.`);setUbNumber(formatted);setAssigned(true);setMessage(`${formatted} is ready. Enter Misc Service Details & Rates below.`)}
 function update(rowId:string,patch:Partial<Row>){setRows((current)=>current.map((row)=>row.rowId===rowId?{...row,...patch}:row))}function add(){setRows((current)=>[...current,newRow()])}function remove(rowId:string){setRows((current)=>{const next=current.filter((row)=>row.rowId!==rowId);return next.length?next:[newRow()]})}
 function lineInputs():MiscBookingLineInput[]{return rows.filter(hasData).map((row)=>({serviceName:row.serviceName.trim(),paxCount:whole(row.paxCount),ratePerPerson:Math.max(0,num(row.ratePerPerson)),roe:row.roe.trim()?Math.max(0,num(row.roe)):null}))}
 function input():MiscBookingInput{return{transactionType:tx,counterpartyId,transactionDate:bookingDate,ubNumber,lines:lineInputs()}}
 function syncOperational(existing=operationalRows){setOperationalRows(rows.filter(hasData).map((_,index)=>existing.find((item)=>item.serviceSortOrder===index)||{rowId:crypto.randomUUID(),serviceSortOrder:index,serviceDate:"",referenceVoucher:"",contact:"",instructions:""}))}
 async function saveCommercial(){if(!assigned)return setError("Create / Assign the Booking UB first.");const active=rows.filter(hasData);if(active.some((row)=>!row.familyHead.trim()))return setError("Passenger / Family Head is required for each Misc service row.");setBusy(true);setError("");try{let id=editingId;if(id){await updateMiscBooking(companyId,id,input(),userId);setMessage(`Misc Service Details & Rates for ${ubNumber} updated.`)}else{id=await createMiscBooking(companyId,input(),userId);setEditingId(id);setSaved(true);setMessage(`Misc booking ${ubNumber} saved. Optional service information is now available.`)}await saveMiscFamilyHeads(companyId,id,active.map((row)=>row.familyHead),userId);setSaved(true);syncOperational();await loadEntries(search);await onChanged?.()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function saveDetails(){if(!editingId)return;setBusy(true);setError("");try{await saveMiscOperationalDetails(companyId,editingId,{services:operationalRows.map((row)=>({serviceSortOrder:row.serviceSortOrder,serviceDate:row.serviceDate,referenceVoucher:row.referenceVoucher,contact:row.contact,instructions:row.instructions})),notes},userId);setMessage(`Misc Booking Details for ${ubNumber} saved.`)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function edit(entry:MiscBooking){if(!canEdit||entry.status!=="ACTIVE")return;setTx(entry.transaction_type as BookingTransactionType);setCounterpartyId(entry.counterparty_id);setBookingDate(entry.transaction_date);setUbNumber(entry.ub_number);setUbDigits(bookingDigitsFromUb(entry.ub_number));setAssigned(true);setSaved(true);setDetailsOpen(false);setEditingId(entry.id);const details=await getMiscOperationalDetails(companyId,entry.id);setRows(entry.lines.length?entry.lines.map((line,index)=>({rowId:crypto.randomUUID(),serviceName:line.service_name,familyHead:details.familyHeads[index]||"",paxCount:String(line.pax_count||""),ratePerPerson:String(line.rate_per_person||""),roe:line.currency_mode==="SAR"&&Number(line.roe||0)>0?String(line.roe):""})):[newRow()]);setOperationalRows(details.services.map((item)=>({...item,rowId:crypto.randomUUID()})));setNotes(details.notes);setMode("FORM");setMessage(`Editing Misc booking ${entry.ub_number}. Identity is locked; Sections 02 and 03 save independently.`);window.scrollTo({top:0,behavior:"smooth"})}
 async function voidEntry(entry:MiscBooking){if(!canVoid||entry.status!=="ACTIVE"||busy)return;if(!window.confirm(`Void Misc booking ${entry.ub_number}?`))return;setBusy(true);try{await voidMiscBooking(companyId,entry.id,userId);await loadEntries(search);await onChanged?.();setMessage(`Misc booking ${entry.ub_number} voided.`)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 function updateOperational(rowId:string,patch:Partial<OperationalRow>){setOperationalRows((current)=>current.map((row)=>row.rowId===rowId?{...row,...patch}:row))}

 if(mode==="REGISTER")return <section className="booking-entry-screen bf-page"><div className="booking-screen-toolbar"><button className="booking-back-button" onClick={()=>setMode("FORM")}>← Back to Misc Booking</button><span className="booking-foundation-badge active-engine">MISC REGISTER</span></div><div className="bf-title"><div><span className="eyebrow blue">MISC BOOKING REGISTER</span><h2>Misc Booking Register</h2></div></div><div className="package14-register-controls"><div className="package-register-filter-tabs">{(["ALL","SALE","PURCHASE"] as Filter[]).map((item)=><button key={item} className={filter===item?"active":""} onClick={()=>setFilter(item)}>{item}</button>)}</div><div className="search-box"><input value={search} onChange={(e)=>{setSearch(e.target.value);void loadEntries(e.target.value)}} placeholder="Search UB, service, party/vendor..."/></div></div><div className="party-table-wrap"><table className="party-table"><thead><tr><th>DATE</th><th>UB #</th><th>TYPE</th><th>PARTY / VENDOR</th><th>SERVICES</th><th>TOTAL SAR</th><th>TOTAL PKR</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{visible.map((entry)=><tr key={entry.id}><td>{entry.transaction_date}</td><td><b>{entry.ub_number}</b></td><td>{entry.transaction_type}</td><td>{entry.counterparty_name}</td><td>{entry.lines.map((line)=>`${line.service_name} (${line.pax_count})`).join(" · ")}</td><td>{sar(entry.total_sar)}</td><td>{pkr(entry.total_pkr)}</td><td><span className={`status ${entry.status.toLowerCase()}`}>{entry.status}</span></td><td><div className="row-actions"><button disabled={!canEdit||entry.status!=="ACTIVE"} onClick={()=>void edit(entry)}>Edit / Details</button><button disabled={!canVoid||entry.status!=="ACTIVE"} onClick={()=>void voidEntry(entry)}>Void</button></div></td></tr>)}</tbody></table></div></section>;

 return <section className="booking-entry-screen bf-page package14-page"><div className="booking-screen-toolbar"><button className="booking-back-button" onClick={onBack}>← Back to Booking Services</button><div className="bf-toolbar-actions"><span className={`direction-badge ${tx==="SALE"?"sale":"purchase"}`}>{tx==="SALE"?"SALE TO PARTY":"PURCHASE FROM VENDOR / SUPPLIER"}</span><button className="booking-foundation-badge active-engine" onClick={()=>{setMode("REGISTER");void loadEntries(search)}}>Misc Booking Register</button></div></div><div className="bf-title"><div><span className="eyebrow blue">MISC BOOKING</span><h2>{saved?`Misc Booking — ${ubNumber}`:"New Misc Booking"}</h2><p>Create the UB first, save Misc accounting second, then add optional service references / instructions.</p></div></div>{message&&<div className="alert success">{message}</div>}{error&&<div className="alert error">{error}</div>}
 <ProgressiveBookingIdentity companyId={companyId} userId={userId} transactionType={tx} parties={parties} counterpartyId={counterpartyId} onCounterpartyChange={setCounterpartyId} bookingDate={bookingDate} onBookingDateChange={setBookingDate} ubDigits={ubDigits} onUbDigitsChange={setUbDigits} ubNumber={ubNumber} assigned={assigned} saved={saved} onAssign={assign} onEditHeader={()=>{setAssigned(false);setMessage("")}} onAccountsChanged={onChanged} onError={setError} onMessage={setMessage} serviceLabel="Misc" />
 {assigned&&<section className="bf-card"><div className="bf-section-head"><div><span>02</span><div><b>MISC SERVICE DETAILS & RATES</b><small>Lightweight commercial / accounting services under {ubNumber}</small></div></div><button className="primary small" onClick={add}>+ Service Row</button></div><div className="bf-table-wrap"><table className="bf-table misc-v3-table"><thead><tr><th>SR</th><th>SERVICE NAME</th><th>PASSENGER / FAMILY HEAD</th><th>NO. OF PAX</th><th>RATE / PERSON</th><th>ROE</th><th>TOTAL</th><th>ACTION</th></tr></thead><tbody>{rows.map((row,index)=>{const c=calc(row);return <tr key={row.rowId}><td>{index+1}</td><td><input value={row.serviceName} onChange={(e)=>update(row.rowId,{serviceName:e.target.value})}/></td><td><input value={row.familyHead} onChange={(e)=>update(row.rowId,{familyHead:e.target.value})}/></td><td><input type="number" min="1" value={row.paxCount} onChange={(e)=>update(row.rowId,{paxCount:e.target.value})}/></td><td><div style={{display:"grid",gridTemplateColumns:"46px 1fr",gap:5,alignItems:"center"}}><b>{c.mode}</b><input type="number" min="0" value={row.ratePerPerson} onChange={(e)=>update(row.rowId,{ratePerPerson:e.target.value})}/></div></td><td><input type="number" min="0" value={row.roe} onChange={(e)=>update(row.rowId,{roe:e.target.value})} placeholder="Blank = PKR"/></td><td className="bf-money"><b>{pkr(c.totalPkr)}</b>{c.mode==="SAR"&&<small style={{display:"block"}}>{sar(c.totalSar)}</small>}</td><td><button className="bf-remove" onClick={()=>remove(row.rowId)}>×</button></td></tr>})}</tbody></table></div><div className="bf-summary"><div><small>MISC SERVICES</small><b>{summary.services}</b></div><div><small>TOTAL PAX ENTRIES</small><b>{summary.paxEntries}</b></div><div><small>TOTAL SAR</small><b>{sar(summary.totalSar)}</b></div><div className="grand"><small>GRAND TOTAL PKR</small><b>{pkr(summary.totalPkr)}</b></div></div><div className="package14-commercial-actions">{saved&&<button className="secondary" onClick={reset}>+ New Misc Booking</button>}<button className="primary" disabled={busy||(!editingId&&!canCreate)||(!!editingId&&!canEdit)} onClick={()=>void saveCommercial()}>{busy?"Saving...":editingId?`Update Misc Service Details & Rates — ${ubNumber}`:`Save Misc Booking — ${ubNumber}`}</button></div></section>}
 {saved&&editingId&&<section className={`package14-additional ${detailsOpen?"open":"closed"}`}><button className="package14-additional-toggle" onClick={()=>{const next=!detailsOpen;setDetailsOpen(next);if(next)syncOperational()}}><span className="package14-step-purple">03</span><div><b>MISC BOOKING DETAILS — {ubNumber}</b><small>Optional service date, reference / voucher, contact and instructions.</small></div><span className="package14-optional">OPTIONAL</span><strong>{detailsOpen?"Close Details ▲":"+ Open Details ▼"}</strong></button>{detailsOpen&&<div className="package14-additional-body bf-operational-body"><div className="bf-subsection"><div className="bf-subsection-head"><div><b>MISC SERVICE INFORMATION</b><small>One information row is synchronized from each Section 02 service.</small></div><button className="primary small" onClick={()=>syncOperational()}>Sync from Section 02</button></div><div className="bf-table-wrap"><table className="bf-table"><thead><tr><th>SR</th><th>SERVICE</th><th>SERVICE DATE</th><th>REFERENCE / VOUCHER</th><th>CONTACT</th><th>INSTRUCTIONS</th></tr></thead><tbody>{operationalRows.map((op,index)=>{const source=rows.filter(hasData)[op.serviceSortOrder];return <tr key={op.rowId}><td>{index+1}</td><td><b>{source?.serviceName||"—"}</b></td><td><input type="date" value={op.serviceDate} onChange={(e)=>updateOperational(op.rowId,{serviceDate:e.target.value})}/></td><td><input value={op.referenceVoucher} onChange={(e)=>updateOperational(op.rowId,{referenceVoucher:e.target.value})}/></td><td><input value={op.contact} onChange={(e)=>updateOperational(op.rowId,{contact:e.target.value})}/></td><td><input value={op.instructions} onChange={(e)=>updateOperational(op.rowId,{instructions:e.target.value})}/></td></tr>})}</tbody></table></div></div><div className="bf-details-grid"><label className="wide">General Notes<textarea rows={4} value={notes} onChange={(e)=>setNotes(e.target.value)}/></label></div><div className="package14-details-actions"><span>Misc remains intentionally lightweight and general-purpose.</span><button className="primary" disabled={busy||!canEdit} onClick={()=>void saveDetails()}>{busy?"Saving...":`Save Misc Details — ${ubNumber}`}</button></div></div>}</section>}
 {!assigned&&<div className="package14-next-step">Create / Assign a Booking UB to unlock Misc Service Details & Rates.</div>}{assigned&&!saved&&<div className="package14-next-step">Save Section 02 to activate the Misc booking and unlock Optional Misc Booking Details.</div>}
 </section>;
}
