import { useEffect, useMemo, useState } from "react";
import type { BookingTransactionType, Party } from "./db";
import { createMiscBooking, getMiscBookings, initMiscDatabase, updateMiscBooking, voidMiscBooking, type MiscBooking, type MiscBookingInput, type MiscBookingLineInput } from "./miscDb";
import ProgressiveBookingIdentity from "./ProgressiveBookingIdentity";
import { bookingDigitsFromUb, normalizeBookingUb } from "./bookingUb";
import { getMiscAdditionalDetails, updateMiscAdditionalDetails } from "./ProgressiveBookingDb";

type Props={companyId:string;parties:Party[];transactionType:BookingTransactionType;userId?:string;canCreate?:boolean;canEdit?:boolean;canVoid?:boolean;onBack:()=>void;onChanged?:()=>void|Promise<void>};
type Row={rowId:string;serviceName:string;paxCount:string;ratePerPerson:string;roe:string};type Mode="FORM"|"REGISTER";type Filter="ALL"|BookingTransactionType;
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`} function newRow():Row{return{rowId:crypto.randomUUID(),serviceName:"",paxCount:"",ratePerPerson:"",roe:""}} function num(v:string){const n=Number(v);return Number.isFinite(n)?n:0} function whole(v:string){return Math.max(0,Math.trunc(num(v)))} function pkr(v:number){return `Rs ${Number(v||0).toLocaleString("en-PK",{maximumFractionDigits:2})}`} function sar(v:number){return `SAR ${Number(v||0).toLocaleString("en-PK",{maximumFractionDigits:2})}`}
function calc(r:Row){const pax=whole(r.paxCount),rate=Math.max(0,num(r.ratePerPerson)),roe=Math.max(0,num(r.roe)),base=rate*pax;return roe>0?{mode:"SAR" as const,pax,totalSar:base,totalPkr:base*roe,roe}:{mode:"PKR" as const,pax,totalSar:0,totalPkr:base,roe:0}} function hasData(r:Row){return Boolean(r.serviceName.trim()||r.paxCount.trim()||r.ratePerPerson.trim()||r.roe.trim())}

export default function MiscBookingFlowV2({companyId,parties,transactionType,userId="",canCreate=true,canEdit=true,canVoid=true,onBack,onChanged}:Props){
 const[mode,setMode]=useState<Mode>("FORM");const[tx,setTx]=useState<BookingTransactionType>(transactionType);const[counterpartyId,setCounterpartyId]=useState("");const[bookingDate,setBookingDate]=useState(localDate());const[ubDigits,setUbDigits]=useState("");const[ubNumber,setUbNumber]=useState("");const[assigned,setAssigned]=useState(false);const[saved,setSaved]=useState(false);const[detailsOpen,setDetailsOpen]=useState(false);const[rows,setRows]=useState<Row[]>([newRow()]);const[notes,setNotes]=useState("");const[entries,setEntries]=useState<MiscBooking[]>([]);const[editingId,setEditingId]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const[search,setSearch]=useState("");const[filter,setFilter]=useState<Filter>("ALL");
 useEffect(()=>{if(!editingId)setTx(transactionType)},[transactionType,editingId]);useEffect(()=>{void(async()=>{try{await initMiscDatabase();await loadEntries("")}catch(e){setError(e instanceof Error?e.message:String(e))}})()},[companyId]);
 const summary=useMemo(()=>{let services=0,paxEntries=0,totalSar=0,totalPkr=0;rows.forEach(r=>{if(!hasData(r))return;const c=calc(r);services++;paxEntries+=c.pax;totalSar+=c.totalSar;totalPkr+=c.totalPkr});return{services,paxEntries,totalSar,totalPkr}},[rows]); const visible=entries.filter(e=>filter==="ALL"||e.transaction_type===filter);
 async function loadEntries(q=search){try{setEntries(await getMiscBookings(companyId,q))}catch(e){setError(e instanceof Error?e.message:String(e))}}
 function reset(){setTx(transactionType);setCounterpartyId("");setBookingDate(localDate());setUbDigits("");setUbNumber("");setAssigned(false);setSaved(false);setDetailsOpen(false);setRows([newRow()]);setNotes("");setEditingId(null);setError("");setMessage("")}
 function assign(formatted:string){setError("");if(!counterpartyId)return setError(tx==="SALE"?"Select a Party / Customer first.":"Select a Vendor / Supplier first.");if(!bookingDate)return setError("Date of Booking is required.");if(!formatted)return setError("Enter a booking number using 1 to 4 digits.");const dup=entries.find(e=>normalizeBookingUb(e.ub_number)===formatted&&(tx==="SALE"?e.transaction_type==="SALE":e.transaction_type==="PURCHASE"&&e.counterparty_id===counterpartyId));if(dup)return setError(tx==="SALE"?`${formatted} already has a Misc Sale booking.`:`This Vendor already has a Misc Purchase booking for ${formatted}.`);setUbNumber(formatted);setAssigned(true);setMessage(`${formatted} is ready. Enter Misc Service Details below.`)}
 function update(id:string,patch:Partial<Row>){setRows(c=>c.map(r=>r.rowId===id?{...r,...patch}:r))} function add(){setRows(c=>[...c,newRow()])} function remove(id:string){setRows(c=>{const n=c.filter(r=>r.rowId!==id);return n.length?n:[newRow()]})}
 function lineInputs():MiscBookingLineInput[]{return rows.filter(hasData).map(r=>({serviceName:r.serviceName.trim(),paxCount:whole(r.paxCount),ratePerPerson:Math.max(0,num(r.ratePerPerson)),roe:r.roe.trim()?Math.max(0,num(r.roe)):null}))} function input():MiscBookingInput{return{transactionType:tx,counterpartyId,transactionDate:bookingDate,ubNumber,lines:lineInputs()}}
 async function saveCommercial(){if(!assigned)return setError("Create / Assign the Booking UB first.");setBusy(true);setError("");try{if(editingId){await updateMiscBooking(companyId,editingId,input(),userId);setMessage(`Misc Service Details for ${ubNumber} updated.`)}else{const id=await createMiscBooking(companyId,input(),userId);setEditingId(id);setSaved(true);setMessage(`Misc booking ${ubNumber} saved. Optional Misc Booking Details are now available.`)}setSaved(true);await loadEntries(search);await onChanged?.()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function saveDetails(){if(!editingId)return;setBusy(true);setError("");try{await updateMiscAdditionalDetails(companyId,editingId,notes,userId);setMessage(`Misc Booking Details for ${ubNumber} saved.`)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function edit(e:MiscBooking){if(!canEdit||e.status!=="ACTIVE")return;setTx(e.transaction_type as BookingTransactionType);setCounterpartyId(e.counterparty_id);setBookingDate(e.transaction_date);setUbNumber(e.ub_number);setUbDigits(bookingDigitsFromUb(e.ub_number));setAssigned(true);setSaved(true);setDetailsOpen(false);setRows(e.lines.length?e.lines.map(l=>({rowId:crypto.randomUUID(),serviceName:l.service_name,paxCount:String(l.pax_count||""),ratePerPerson:String(l.rate_per_person||""),roe:l.currency_mode==="SAR"&&Number(l.roe||0)>0?String(l.roe):""})):[newRow()]);setEditingId(e.id);setNotes(await getMiscAdditionalDetails(companyId,e.id));setMode("FORM");setMessage(`Editing Misc booking ${e.ub_number}. Identity is locked; Section 02 and Section 03 save independently.`);window.scrollTo({top:0,behavior:"smooth"})}
 async function voidEntry(e:MiscBooking){if(!canVoid||e.status!=="ACTIVE"||busy)return;if(!window.confirm(`Void Misc booking ${e.ub_number}?`))return;setBusy(true);try{await voidMiscBooking(companyId,e.id,userId);await loadEntries(search);await onChanged?.();setMessage(`Misc booking ${e.ub_number} voided.`)}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}}

 if(mode==="REGISTER")return <section className="booking-entry-screen misc13-page"><div className="booking-screen-toolbar"><button className="booking-back-button" onClick={()=>setMode("FORM")}>← Back to Misc Booking</button><span className="booking-foundation-badge active-engine">MISC REGISTER</span></div><div className="misc13-title"><div><span className="eyebrow blue">MISC BOOKING REGISTER</span><h2>Misc Booking Register</h2></div></div><div className="misc13-register-controls"><div>{(["ALL","SALE","PURCHASE"] as Filter[]).map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="search-box"><input value={search} onChange={e=>{setSearch(e.target.value);void loadEntries(e.target.value)}} placeholder="Search UB, service, party/vendor..."/></div></div><div className="party-table-wrap"><table className="party-table"><thead><tr><th>DATE</th><th>UB #</th><th>TYPE</th><th>PARTY / VENDOR</th><th>SERVICES</th><th>TOTAL SAR</th><th>TOTAL PKR</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{visible.map(e=><tr key={e.id}><td>{e.transaction_date}</td><td><b>{e.ub_number}</b></td><td>{e.transaction_type}</td><td>{e.counterparty_name}</td><td>{e.lines.map(l=>`${l.service_name} (${l.pax_count})`).join(" · ")}</td><td>{sar(e.total_sar)}</td><td>{pkr(e.total_pkr)}</td><td><span className={`status ${e.status.toLowerCase()}`}>{e.status}</span></td><td><div className="row-actions"><button disabled={!canEdit||e.status!=="ACTIVE"} onClick={()=>void edit(e)}>Edit / Details</button><button disabled={!canVoid||e.status!=="ACTIVE"} onClick={()=>void voidEntry(e)}>Void</button></div></td></tr>)}</tbody></table></div></section>;

 return <section className="booking-entry-screen misc13-page package14-page"><div className="booking-screen-toolbar"><button className="booking-back-button" onClick={onBack}>← Back to Booking Services</button><div style={{display:"flex",gap:10,alignItems:"center"}}><span className={`direction-badge ${tx==="SALE"?"sale":"purchase"}`}>{tx==="SALE"?"SALE TO PARTY":"PURCHASE FROM VENDOR / SUPPLIER"}</span><button className="booking-foundation-badge active-engine" onClick={()=>{setMode("REGISTER");void loadEntries(search)}}>Misc Booking Register</button></div></div><div className="misc13-title"><div><span className="eyebrow blue">MISC BOOKING</span><h2>{saved?`Misc Booking — ${ubNumber}`:"New Misc Booking"}</h2><p>Create the UB first, save Misc calculations second, then add optional information.</p></div></div>{message&&<div className="alert success">{message}</div>}{error&&<div className="alert error">{error}</div>}
 <ProgressiveBookingIdentity companyId={companyId} userId={userId} transactionType={tx} parties={parties} counterpartyId={counterpartyId} onCounterpartyChange={setCounterpartyId} bookingDate={bookingDate} onBookingDateChange={setBookingDate} ubDigits={ubDigits} onUbDigitsChange={setUbDigits} ubNumber={ubNumber} assigned={assigned} saved={saved} onAssign={assign} onEditHeader={()=>{setAssigned(false);setMessage("")}} onAccountsChanged={onChanged} onError={setError} onMessage={setMessage} serviceLabel="Misc" />
 {assigned&&<section className="misc13-card"><div className="misc13-section-head misc13-row-head"><div><span>2</span><b>MISC SERVICE DETAILS & RATES</b></div><button className="primary small" onClick={add}>+ Add Service Row</button></div><div className="misc13-table-wrap"><table className="misc13-table"><thead><tr><th>SR</th><th>SERVICE NAME</th><th>NO. OF PAX</th><th>RATE / PERSON</th><th>ROE</th><th>TOTAL</th><th></th></tr></thead><tbody>{rows.map((r,i)=>{const c=calc(r);return <tr key={r.rowId}><td>{i+1}</td><td><input className="misc13-service" value={r.serviceName} onChange={e=>update(r.rowId,{serviceName:e.target.value})}/></td><td><input type="number" value={r.paxCount} onChange={e=>update(r.rowId,{paxCount:e.target.value})}/></td><td className="misc13-rate-wrap"><span className={`misc13-currency-chip ${c.mode==="SAR"?"sar":""}`}>{c.mode}</span><input type="number" value={r.ratePerPerson} onChange={e=>update(r.rowId,{ratePerPerson:e.target.value})}/></td><td><input type="number" value={r.roe} onChange={e=>update(r.rowId,{roe:e.target.value})} placeholder="Blank = PKR"/></td><td className="misc13-total"><b>{pkr(c.totalPkr)}</b>{c.mode==="SAR"&&<small>{sar(c.totalSar)}</small>}</td><td><button className="misc13-remove" onClick={()=>remove(r.rowId)}>×</button></td></tr>})}</tbody></table></div><section className="misc13-summary" style={{margin:14}}><div><small>MISC SERVICES</small><b>{summary.services}</b></div><div><small>TOTAL PAX ENTRIES</small><b>{summary.paxEntries}</b></div><div><small>TOTAL SAR</small><b>{sar(summary.totalSar)}</b></div><div className="grand"><small>GRAND TOTAL PKR</small><b>{pkr(summary.totalPkr)}</b></div></section><div className="package14-commercial-actions">{saved&&<button className="secondary" onClick={reset}>+ New Misc Booking</button>}<button className="primary" disabled={busy||(!editingId&&!canCreate)||(!!editingId&&!canEdit)} onClick={()=>void saveCommercial()}>{busy?"Saving...":editingId?`Update Misc Details & Rates — ${ubNumber}`:`Save Misc Booking — ${ubNumber}`}</button></div></section>}
 {saved&&editingId&&<section className={`package14-additional ${detailsOpen?"open":"closed"}`}><button className="package14-additional-toggle" onClick={()=>setDetailsOpen(v=>!v)}><span className="package14-step-purple">03</span><div><b>MISC BOOKING DETAILS — {ubNumber}</b><small>Optional general information. This section does not change Misc calculations.</small></div><span className="package14-optional">OPTIONAL</span><strong>{detailsOpen?"Close Details ▲":"+ Open Details ▼"}</strong></button>{detailsOpen&&<div className="package14-additional-body"><div className="package14-details-grid"><label className="wide">Notes / Instructions<textarea rows={5} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional service instructions or internal notes..."/></label></div><div className="package14-details-actions"><span>Optional — can be completed later.</span><button className="primary" disabled={busy||!canEdit} onClick={()=>void saveDetails()}>{busy?"Saving...":`Save Misc Details — ${ubNumber}`}</button></div></div>}</section>}
 {!assigned&&<div className="package14-next-step">Create / Assign a Booking UB to unlock Misc Service Details & Rates.</div>}{assigned&&!saved&&<div className="package14-next-step">Save Section 02 to activate the Misc booking and unlock Optional Misc Booking Details.</div>}
 </section>;
}
